### ISSUE TITLE
Process.env?

### ISSUE THREAD

**Issue by akita-programs** [DestinyItemManager/dim-api#47]
![image](https://user-images.githubusercontent.com/73960514/119030900-78de9800-b978-11eb-8162-e1b4fd5c23f2.png)

I'm confused to as why this is using process.env to load a .env file, it's purpose is not to load environment files, but to return the node environment of the process. Shouldn't you be using a package like dotenv?

**Comment by bhollis** [comment]
This is used to read environment variables. dotenv is a separate thing that loads the contents of files into the environment. In this case, JWT_SECRET is provided through the process environment, populated by Kubernetes.
